# Generated by Django 2.1.3 on 2018-12-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_latitude',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_longitude',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=20),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_name',
            field=models.CharField(default='nul', max_length=500),
            preserve_default=False,
        ),
    ]
