# Generated by Django 2.1.3 on 2018-12-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181209_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=100)),
            ],
        ),
    ]
