# Generated by Django 2.1.3 on 2018-12-11 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventregistered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistered',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.EventGroups'),
        ),
    ]
