# Generated by Django 2.1.3 on 2018-12-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20181211_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistered',
            name='group',
            field=models.CharField(max_length=100),
        ),
    ]
