# Generated by Django 2.1.3 on 2018-12-11 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20181211_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistered',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
